### ISSUE TITLE
Create my own libs.

### ISSUE THREAD

**Issue by ahorawzy** [pzhaonet/sinx#4]
I like this package, which can help me take a break during work.
However I find it's a little redundant to load my own database via read.sinx(file="D:/......") because I have to type the whole route each time when I want to use sinx.
Can I save my own libs so that it can be available like read.sinx(lib="myownlib").
And can I change the default lib to Chinese or tangshi?

**Comment by pzhaonet** [comment]
Sure you can. Just write your own function to simplify it as you like. For example, you can write:

```
mm <- function(){
ftns <- sinx::read.sinx(file="D:/......")
  sinx::sinx(sinxs.data = ftns)
} 
```

then you can run `mm()` for short.

**Comment by ahorawzy** [comment]
Get it! Thank you!
